create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
create table concept (id bigint not null auto_increment, date_created datetime, date_last_reviewed datetime, done bit not null, explanation varchar(255) not null, name varchar(100), reviewed bit not null, simplified bit not null, user_id bigint, primary key (id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), primary key (id)) engine=InnoDB
