#TODO: Create a Prod yaml and Dev yaml, The dev yaml can be shared on git.

facebook:
  client:
    clientId: 1811021145627325
    clientSecret: 3f47d22c8940acf0f5796b88f33b6515
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me
    
google:
  client:
    clientId: 947387101632-vf0tfug3eduuvpu50qftvjistlj9mkk9.apps.googleusercontent.com
    clientSecret: UuC40Ye_kuyLPvLm_0NZtqJ8
    accessTokenUri: https://oauth2.googleapis.com/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    authenticationScheme: query
    scope: email
    tokenName: oauth_token
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
    


logging:
  level:
    org.springframework.security: DEBUG