version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    
    working_directory: ~/concetto
     
    steps:
      - checkout

      # Docker Layer Caching is not available in the free version.

      #- setup_remote_docker:
      #    docker_layer_caching: true
    
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
         

      - restore_cache:
          keys:
            - concetto-{{ checksum "pom.xml" }}
       
      - run: mvn dependency:go-offline
       
      - save_cache:
         paths:
           - ~/.m2
         key: concetto-{{ checksum "pom.xml" }}

      - run: mvn clean test -Dspring.profiles.active=test

    #Package into Jar.
      - run: mvn clean package -Dspring.profiles.active=prod -DskipTests

    #Build a docker image using jib.
      - run: mvn clean compile jib:build -Dimage=domgarr/concetto:$CIRCLE_BUILD_NUM -Dspring.profiles.active=prod -DskipTests
       
      - store_artifacts:
          path: target/classes
          destination: concetto