spring:
  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USER_PROD}
    password: ${DB_PASSWORD_PROD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
